# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (every night at 4am)
  schedule: [{cron: "0 4 * * *"}]
  # Line below let you run workflow manually
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN2 }}

          # Options
          user: rstkhldntsk
          template: classic
          base: header, activity, community, repositories, metadata

          config_display: large

          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: data, markup, programming, prose
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: data, markup, programming, prose
          plugin_languages_recent_days: 60
          plugin_languages_recent_load: 1000
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          plugin_lines: yes
